package com.example.accessingdatamysql;

import javax.management.ConstructorParameters;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.jdbc.core.JdbcTemplate;
import java.util.List;
import java.util.Map;
import java.lang.String;
import java.lang.Object;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @Autowired
  private JdbcTemplate jdbcTemplate;



  @PostMapping(path="/add") // POST http://localhost:8080/demo/add
  public @ResponseBody String addNewUser (@RequestParam String name
      , @RequestParam String email) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();
    n.setName(name);
    n.setEmail(email);
    userRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all") // GET http://localhost:8080/demo/all
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }

  @GetMapping(path="/ver/{id}") // GET http://localhost:8080/demo/all
  public @ResponseBody User getUser(@PathVariable("id") Integer id) {
    return userRepository.findById(id).orElse(null);
  }

  @PutMapping(path="/edit")
  public @ResponseBody String editUser(@RequestParam Integer id, @RequestParam String name, @RequestParam String email) {
    User user = userRepository.findById(id).orElse(null);
    if (user != null) {
      user.setName(name);
      user.setEmail(email);
      userRepository.save(user);
      return "Edited";
    }
    return "Not found";
  }

  @DeleteMapping(path="/del")
  public @ResponseBody String deleteUser(@RequestParam Integer id) {
    User user = userRepository.findById(id).orElse(null);
    if (user != null) {
      userRepository.delete(user);
      return "Deleted";
    }
    return "Not found";
  }

  @GetMapping(path="/get/report")
  public @ResponseBody List getReport() {
    String sql = "SELECT CONCAT(name, ' ==> ', email) as reporte FROM user";
    List<Map<String, Object>> queryResult = jdbcTemplate.queryForList(sql);
    return queryResult;
  }




}